from enum import Enum


class NotificationType(str, Enum):
    LEAVE_REQUEST = "LEAVE_REQUEST"
    LEAVE_APPROVED = "LEAVE_APPROVED"
    LEAVE_REJECTED = "LEAVE_REJECTED"
    LEAVE_CANCELLED = "LEAVE_CANCELLED"
    HOLIDAY_ANNOUNCEMENT = "HOLIDAY_ANNOUNCEMENT"
    PERFORMANCE_UPDATE = "PERFORMANCE_UPDATE"
    GENERAL_ANNOUNCEMENT = "GENERAL_ANNOUNCEMENT"
    PROJECT_UPDATE = "PROJECT_UPDATE"
    TASK_UPDATE = "TASK_UPDATE"
    ATTENDANCE_UPDATE = "ATTENDANCE_UPDATE"
    PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST"
    COMPANY_ANNOUNCEMENT = "COMPANY_ANNOUNCEMENT"
    PROJECT_ANNOUNCEMENT = "PROJECT_ANNOUNCEMENT"
    COMPLAINT_SUBMITTED = "COMPLAINT_SUBMITTED"
    COMPLAINT_UPDATED = "COMPLAINT_UPDATED"
    COMPLAINT_RESOLVED = "COMPLAINT_RESOLVED"
