"""add_announcements_module

Revision ID: 7b74d90b70f2
Revises: e8a91f427b3d
Create Date: 2026-09-05 11:49:49.900250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b74d90b70f2'
down_revision: Union[str, Sequence[str], None] = 'e8a91f427b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new enum values to Postgres native enums if they exist
    op.execute("ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'ANNOUNCEMENT_CREATED'")
    op.execute("ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'ANNOUNCEMENT_UPDATED'")
    op.execute("ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'ANNOUNCEMENT_PUBLISHED'")
    op.execute("ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'ANNOUNCEMENT_ARCHIVED'")
    op.execute("ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'ANNOUNCEMENT_READ'")

    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'COMPANY_ANNOUNCEMENT'")
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'PROJECT_ANNOUNCEMENT'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('announcement_type', sa.Enum('HOLIDAY', 'SALARY', 'HR_NOTICE', 'COMPANY_UPDATE', 'GENERAL', name='announcement_type'), nullable=False),
    sa.Column('priority', sa.Enum('NORMAL', 'IMPORTANT', 'URGENT', name='announcement_priority'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='announcement_status'), nullable=False),
    sa.Column('announcement_scope', sa.Enum('COMPANY', 'PROJECT', name='announcement_scope'), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_announcement_scope'), 'announcements', ['announcement_scope'], unique=False)
    op.create_index(op.f('ix_announcements_announcement_type'), 'announcements', ['announcement_type'], unique=False)
    op.create_index(op.f('ix_announcements_priority'), 'announcements', ['priority'], unique=False)
    op.create_index(op.f('ix_announcements_project_id'), 'announcements', ['project_id'], unique=False)
    op.create_index(op.f('ix_announcements_status'), 'announcements', ['status'], unique=False)
    op.create_index(op.f('ix_announcements_title'), 'announcements', ['title'], unique=False)
    op.create_table('announcement_reads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'employee_id', name='uq_announcement_employee_read')
    )
    op.create_index(op.f('ix_announcement_reads_announcement_id'), 'announcement_reads', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_announcement_reads_employee_id'), 'announcement_reads', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_assignments_project_role_id'), table_name='project_assignments')
    op.create_index(op.f('ix_unique_active_project_assignment'), 'project_assignments', ['project_id', 'employee_id'], unique=True, postgresql_where="(status = 'ACTIVE'::assignment_status)")
    op.create_index(op.f('ix_project_assignments_role_id'), 'project_assignments', ['project_role_id'], unique=False)
    op.drop_index(op.f('ix_announcement_reads_employee_id'), table_name='announcement_reads')
    op.drop_index(op.f('ix_announcement_reads_announcement_id'), table_name='announcement_reads')
    op.drop_table('announcement_reads')
    op.drop_index(op.f('ix_announcements_title'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_status'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_project_id'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_priority'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_announcement_type'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_announcement_scope'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
