"""add_leave_management

Revision ID: fd155b616e21
Revises: d48bc759d70c
Create Date: 2026-09-04 13:57:48.228128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd155b616e21'
down_revision: Union[str, Sequence[str], None] = 'd48bc759d70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # --------------------------------------------------------
    # Extend audit_action enum safely
    # --------------------------------------------------------
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'LEAVE_APPLIED'")
        op.execute("ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'LEAVE_APPROVED'")
        op.execute("ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'LEAVE_REJECTED'")
        op.execute("ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'LEAVE_CANCELLED'")
        op.execute("ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'LEAVE_TYPE_CREATED'")
        op.execute("ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'LEAVE_TYPE_UPDATED'")
        op.execute("ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'LEAVE_TYPE_ACTIVATED'")
        op.execute("ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'LEAVE_TYPE_DEACTIVATED'")
        op.execute("ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'LEAVE_BALANCE_UPDATED'")


    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_types',

    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('annual_allocation', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('requires_document', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('annual_allocation >= 0', name='chk_leave_types_allocation_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_types_name'), 'leave_types', ['name'], unique=True)
    op.create_table('leave_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('allocated_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('used_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('pending_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('allocated_days >= 0', name='chk_leave_balance_allocated_positive'),
    sa.CheckConstraint('pending_days >= 0', name='chk_leave_balance_pending_positive'),
    sa.CheckConstraint('used_days + pending_days <= allocated_days', name='chk_leave_balance_total_usage'),
    sa.CheckConstraint('used_days >= 0', name='chk_leave_balance_used_positive'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'leave_type_id', 'year', name='uq_leave_balance_employee_type_year')
    )
    op.create_index(op.f('ix_leave_balances_employee_id'), 'leave_balances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_balances_leave_type_id'), 'leave_balances', ['leave_type_id'], unique=False)
    op.create_index(op.f('ix_leave_balances_year'), 'leave_balances', ['year'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('duration', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('start_day_type', sa.Enum('FULL_DAY', 'FIRST_HALF', 'SECOND_HALF', name='leave_day_type'), nullable=False),
    sa.Column('end_day_type', sa.Enum('FULL_DAY', 'FIRST_HALF', 'SECOND_HALF', name='leave_day_type'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leave_status'), nullable=False),
    sa.Column('hr_remarks', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('duration > 0', name='chk_leave_requests_duration'),
    sa.CheckConstraint('start_date <= end_date', name='chk_leave_requests_dates'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_created_at'), 'leave_requests', ['created_at'], unique=False)
    op.create_index('ix_leave_requests_dates', 'leave_requests', ['start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False)
    op.create_index('ix_leave_requests_employee_status', 'leave_requests', ['employee_id', 'status'], unique=False)
    op.create_index(op.f('ix_leave_requests_end_date'), 'leave_requests', ['end_date'], unique=False)
    op.create_index(op.f('ix_leave_requests_leave_type_id'), 'leave_requests', ['leave_type_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_start_date'), 'leave_requests', ['start_date'], unique=False)
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    op.create_table('leave_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('leave_request_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['leave_request_id'], ['leave_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_attachments_leave_request_id'), 'leave_attachments', ['leave_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_attachments_leave_request_id'), table_name='leave_attachments')
    op.drop_table('leave_attachments')
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_start_date'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_leave_type_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_end_date'), table_name='leave_requests')
    op.drop_index('ix_leave_requests_employee_status', table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_employee_id'), table_name='leave_requests')
    op.drop_index('ix_leave_requests_dates', table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_created_at'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_leave_balances_year'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_leave_type_id'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_employee_id'), table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_index(op.f('ix_leave_types_name'), table_name='leave_types')
    op.drop_table('leave_types')
    # ### end Alembic commands ###
